version: "3.3"
services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/project/
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: orbis-api-db
    redis:
        image: redis
        container_name: redis
        command: redis-server --requirepass wu1ohr5Eipun8Eim
        ports:
            - 6379:6379